# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WalgWalg-front_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalgWalg-front_ios
  pod 'FSCalendar'
  pod 'JJFloatingActionButton'
  pod 'MaterialComponents/Buttons'
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 4.0'
end
